early_chinese_terms = {'china', 'chinese', 'chinamen', 'chinaman', 'indochina', 'indochinese',
                       'asia', 'asian', 'asians', 'asiatic', 'asiatics',
                       'orient', 'oriental', 'orientals', 'celestial', 'celestials',
                       'cooly', 'coolie', 'coolys', 'coolies',
                       'mongolian', 'mongolians', 'mongol', 'mongols'}
early_chinese_terms.update([t + 'american' for t in early_chinese_terms] + [t + 'americans' for t in early_chinese_terms])

european_terms = {'english', 'british', 'french',  'european',
                  'canadian', 'german',  'germanic', 'irish',
                  'celtic', 'scottish', 'swedish', 'norwegian', 'finnish',
                  'danish', 'belgian', 'dutch', 'swiss', 'scandinavian',
                  'austrian', 'austrohungarian', 'italian', 'portuguese',
                  'cypriot', 'yugoslavian',
                  'greek',
                  'turkish',
                  'albanian',
                  'slav',
                  'slavic',
                  'yugoslav',
                  'yugoslavian',
                  'serbian',
                  'serb',
                  'croatian',
                  'bosnian',
                  'lithuanian',
                  'latvian',
                  'bohemian',
                  'estonian',
                  'hungarian',
                  'ukrainian',
                  'ukranian',
                  'bulgarian',
                  'armenian',
                  'slovakian',
                  'romanian',
                  'rumanian',
                  'roumanian',
                  'czech',
                  'czechoslovak',
                  'czechoslovakian',
                  'polish',
                  'protestant',
                  'catholic',
                  'jew',
                  'jewish',
                  'englishman',
                  'englishmen',
                  'brits',
                  'frenchmen',
                  'frenchman',
                  'europeans',
                  'canadians',
                  'germans',
                  'irishmen',
                  'irishman',
                  'celts',
                  'scotsman',
                  'scotsman',
                  'swedes',
                  'norwegians',
                  'finns',
                  'belgians',
                  'scandinavians',
                  'austrians',
                  'danes',
                  'italians',
                  'cypriots',
                  'spaniards',
                  'yugoslavians',
                  'greeks',
                  'turks',
                  'slavs',
                  'yugoslavs',
                  'serbians',
                  'serbs',
                  'croatians',
                  'bosnians',
                  'lithuanians',
                  'latvians',
                  'bohemians',
                  'estonians',
                  'hungarians',
                  'ukrainians',
                  'bulgarians',
                  'armenians',
                  'slovakians',
                  'romanians',
                  'rumanians',
                  'roumanians',
                  'bulgarians',
                  'albanians',
                  'slovaks',
                  'czechs',
                  'czechoslovakians',
                  'protestants',
                  'catholics',
                  'jews',
                  'england', 'britain', 'france',
                  'europe', 'canada', 'germany',
                  'ireland', 'scotland', 'sweden',
                  'norway', 'finland', 'denmark', 'belgium',
                  'holland', 'netherlands', 'switzerland',
                  'scandinavia', 'austria', 'hungary',
                  'italy', 'portugal', 'cyprus',
                  'yugoslavia', 'greece',
                  'albania', 'serbia', 'croatia', 'bosnia',
                  'lithuania', 'latvia', 'bohemia', 'estonia',
                  'ukraine', 'bulgaria', 'armenia', 'solvakia'
                                                    'romania', 'rumania', 'roumania', 'czechoslovakia',
                  'poland', 'vatican'}
european_terms.update([t + 'american' for t in european_terms] + [t + 'americans' for t in european_terms])

modern_mexican_terms = {'mexico', 'mexican', 'mexicans', 'mexica', 'mexicas',
                        'wetback', 'wetbacks', 'bracero', 'braceros'}
modern_mexican_terms.update([t + 'american' for t in modern_mexican_terms] + [t + 'americans' for t in modern_mexican_terms])

modern_asian_terms = {'asians',
                      'asiatics',
                      'orientals',
                      'chinamen',
                      'chinaman',
                      'celestials',
                      'mongolians',
                      'tibetans',
                      'japs',
                      'filipinos',
                      'filipinas',
                      'koreans',
                      'indonesians',
                      'malaysians',
                      'pakistanis',
                      'bangladeshis',
                      'cambodians',
                      'laotians',
                      'hindus',
                      'hindoos',
                      'sikhs',
                      'buddhists',
                      'asian',
                      'oriental',
                      'chinese',
                      'taiwanese',
                      'indochinese',
                      'mongolian',
                      'tibetan',
                      'japanese',
                      'jap',
                      'filipino',
                      'korean',
                      'vietnamese',
                      'indonesian',
                      'cambodian',
                      'malaysian',
                      'pakistani',
                      'bangladeshi',
                      'laotian',
                      'hindu',
                      'hindoo',
                      'sikh',
                      'buddhist',
                      'burmese',
                      'thai',
                      'asia',
                      'orient',
                      'china',
                      'taiwan',
                      'indochina',
                      'mongolia',
                      'tibet',
                      'japan',
                      'philippines',
                      'korea',
                      'vietnam',
                      'cambodia',
                      'malaysia',
                      'pakistan',
                      'bangladesh',
                      'laos',
                      'burma',
                      'myanmar',
                      'thailand'}
modern_asian_terms.update([t + 'american' for t in modern_asian_terms] + [t + 'americans' for t in modern_asian_terms])
